# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Create Release'
description: 'Github Action to create a release for repository'
author: 'yawuling'
branding:
  color: 'blue'
  icon: 'eye'

inputs:
  name:
    description: 'The name of the release'
    required: true
  body:
    description: Text describing the contents of the tag
    required: true
  tag_name:
    description: The name of the tag
    required: true
  prerelease:
    description: true to identify the release as a prerelease. false to identify the release as a full release
    default: false
  draft:
    description: true to create a draft (unpublished) release, false to create a published one
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
